### ISSUE TITLE
I'm not in the dining hall - should be WH3

### ISSUE THREAD

**Issue by cg123** [olin/maraudersmap-client#11]
http://ohack-map.herokuapp.com/ui/index.html?action=place&username=cgoddard&signals%5B00%3A15%3AE8%3AE1%3ACF%5D=23.0&signals%5B00%3A20%3AD8%3A2D%3A65%5D=18.0&signals%5B00%3A15%3AE8%3AE3%3AD7%5D=16.0&signals%5B00%3A20%3AD8%3A28%3AA8%5D=41.0&signals%5B00%3A20%3AD8%3A2D%3A9E%5D=16.0

**Comment by jceipek** [comment]
Your signal strength:
        signals[00:15:E8:E1:CF]=23.0
        signals[00:20:D8:2D:65]=18.0
        signals[00:15:E8:E3:D7]=16.0
        signals[00:20:D8:28:A8]=41.0
        signals[00:20:D8:2D:9E]=16.0

Dining hall bind:
        "00:0b:0e:38:34:00": 17.0, 
        "00:0b:0e:38:34:01": 8.66666666667, 
        "00:20:d8:2d:2c:c1": 21.3333333333, 
        "00:20:d8:2d:2c:c0": 30.6666666667, 
        "00:15:e8:e3:75:81": 35.6666666667, 
        "00:15:e8:e3:75:80": 38.3333333333, 
        "00:20:d8:2d:64:80": 12.6666666667, 
        "00:20:d8:2d:b6:81": 8.66666666667, 
        "00:20:d8:2d:b6:80": 21.0, 
        "00:20:d8:28:a8:02": 4.66666666667, 
        "00:20:d8:2d:85:40": 53.3333333333, 
        "00:20:d8:2d:85:41": 44.0, 
        "00:20:d8:2d:b3:c0": 18.0, 
        "00:20:d8:2d:65:02": 8.0

Note that the dining hall bind signals all contain one extra component in the MAC address. Because no signals matched, you were designated as being at the first bind in the binds database.

Actual issue: Windows MAC addresses do not match Mac OS X; see Issue #12
